title: Default

options:
    icon: page-blank

fields:
    title:
        type: text
        class: form-input-large
        label: '{{page.title}}'
        required: true

    content:
        type: markdown

    published:
        type: checkbox
        label: '{{page.status.published}}'
        default: true

    slug:
        type: slug
        label: '{{page.slug}}'
        suggestion: '{{page.slug.suggestion}}'
        required: true
        readonly@: page.isSlugReadonly
        source: title
        autoUpdate: false

    parent:
        type: page
        label: '{{page.parent}}'
        required: true
        collection@: site.descendants.allowingChildren.withoutPageAndDescendants(page)
        allowSite: true

    template:
        type: template
        required: true
        label: '{{page.template}}'
        default@: site.get('defaultTemplate', 'default')
