title: Default

fields:
    title:
        type: text
        class: form-input-large
        label: '{{page.title}}'
        required: true

    content:
        type: markdown

    published:
        type: checkbox
        label: '{{page.status.published}}'
        default: true

    parent:
        type: page
        access: panel
        label: '{{page.parent}}'

    template:
        type: template
        access: panel
        label: '{{page.template}}'
