title: System

layout:
    type: sections
    sections:
        dateTime:
            collapsible: true
            label: '{{panel.options.system.dateAndTime}}'
            fields: [date.format, date.timeFormat, date.timezone, date.weekStarts]

        languages:
            collapsible: true
            label: '{{panel.options.system.languages}}'
            fields: [languages.available, languages.httpPreferred]

        files:
            collapsible: true
            label: '{{panel.options.system.files}}'
            fields: [files.allowedExtensions]

        cache:
            collapsible: true
            label: '{{panel.options.system.cache}}'
            fields: [cache.enabled, cache.time]

        panel:
            collapsible: true
            label: '{{panel.options.system.adminPanel}}'
            fields: [panel.translation, panel.logoutRedirect, panel.sessionTimeout, panel.colorScheme]

        images:
            collapsible: true
            label: '{{panel.options.system.images}}'
            fields: [images.jpegQuality, images.pngCompression, images.webpQuality, images.jpegProgressive, images.processUploads]

        backup:
            collapsible: true
            label: '{{panel.options.system.backup}}'
            fields: [backup.maxFiles]

fields:
    date.format:
        type: select
        label: '{{panel.options.system.dateAndTime.dateFormat}}'
        import:
            options: 'Formwork\Panel\Utils\DateFormats::date'

    date.timeFormat:
        type: select
        label: '{{panel.options.system.dateAndTime.hourFormat}}'
        import:
            options: 'Formwork\Panel\Utils\DateFormats::hour'

    date.timezone:
        type: select
        label: '{{panel.options.system.dateAndTime.timezone}}'
        import:
            options: 'Formwork\Panel\Utils\DateFormats::timezones'

    date.weekStarts:
        type: select
        label: '{{panel.options.system.dateAndTime.firstWeekday}}'
        options:
            0: '{{panel.options.system.dateAndTime.firstWeekday.sunday}}'
            1: '{{panel.options.system.dateAndTime.firstWeekday.monday}}'

    languages.available:
        type: tags
        label: '{{panel.options.system.languages.availableLanguages}}'
        placeholder: '{{panel.options.system.languages.availableLanguages.noLanguages}}'
        pattern: '^[a-z]{2,3}$'
        translate: [label, placeholder]
        import:
            options: 'Formwork\Languages\LanguageCodes::names'

    languages.httpPreferred:
        type: togglegroup
        label: '{{panel.options.system.languages.preferredLanguage}}'
        options:
            1: '{{panel.options.system.languages.preferredLanguage.enabled}}'
            0: '{{panel.options.system.languages.preferredLanguage.disabled}}'

    files.allowedExtensions:
        type: tags
        label: '{{panel.options.system.files.allowedExtensions}}'
        pattern: '^\.[a-zA-Z0-9]+$'
        required: true

    cache.enabled:
        type: togglegroup
        label: '{{panel.options.system.cache}}'
        options:
            1: '{{panel.options.system.cache.enabled}}'
            0: '{{panel.options.system.cache.disabled}}'

    cache.time:
        type: duration
        label: '{{panel.options.system.cache.time}}'
        min: 900
        step: 900
        intervals: [weeks, days, hours, minutes]
        translate: [label]
        required: true

    panel.translation:
        type: select
        label: '{{panel.options.system.adminPanel.defaultLanguage}}'
        translate: [label]
        import:
            options: 'Formwork\Panel\Panel::availableTranslations'

    panel.logoutRedirect:
        type: togglegroup
        label: '{{panel.options.system.adminPanel.logoutRedirectsTo}}'
        options:
            login: '{{panel.options.system.adminPanel.logoutRedirectsTo.login}}'
            home: '{{panel.options.system.adminPanel.logoutRedirectsTo.home}}'

    panel.sessionTimeout:
        type: duration
        label: '{{panel.options.system.adminPanel.sessionTimeout}}'
        min: 0
        unit: minutes
        intervals: [hours, minutes]
        translate: [label]
        required: true

    panel.colorScheme:
        type: togglegroup
        label: '{{panel.options.system.adminPanel.defaultColorScheme}}'
        options:
            light: '{{panel.options.system.adminPanel.defaultColorScheme.light}}'
            dark: '{{panel.options.system.adminPanel.defaultColorScheme.dark}}'

    images.jpegQuality:
        type: range
        label: '{{panel.options.system.images.jpegQuality}}'
        min: 0
        max: 100
        step: 5

    images.pngCompression:
        type: range
        label: '{{panel.options.system.images.pngCompressionLevel}}'
        min: 0
        max: 9

    images.webpQuality:
        type: range
        label: '{{panel.options.system.images.webpQuality}}'
        min: 0
        max: 100
        step: 5

    images.jpegProgressive:
        type: togglegroup
        label: '{{panel.options.system.images.jpegSaveProgressive}}'
        options:
            1: '{{panel.options.system.images.jpegSaveProgressive.enabled}}'
            0: '{{panel.options.system.images.jpegSaveProgressive.disabled}}'

    images.processUploads:
        type: togglegroup
        label: '{{panel.options.system.images.processUploads}}'
        options:
            1: '{{panel.options.system.images.processUploads.enabled}}'
            0: '{{panel.options.system.images.processUploads.disabled}}'

    backup.maxFiles:
        type: select
        label: '{{panel.options.system.backup.backupFilesToKeep}}'
        options:
            5: 5
            10: 10
            15: 15
            20: 20
