extends:
    - stylelint-config-standard-scss
ignoreFiles:
    - "./assets/css/*.css"
    - "./assets/scss/*.scss"
    - "./assets/scss/vendor/*.scss"
plugins:
    - stylelint-scss
    - stylelint-order
rules:
    at-rule-empty-line-before:
        - always
        - except:
              - first-nested
          ignore:
              - after-comment
          ignoreAtRules:
              - if
              - import
              - include
              - else
              - extend
              - media
    at-rule-no-unknown:
    at-rule-no-vendor-prefix: true
    color-function-notation:
    color-hex-length: short
    color-named: never
    comment-whitespace-inside: always
    declaration-block-no-duplicate-custom-properties: true
    declaration-block-no-duplicate-properties: true
    font-family-no-duplicate-names: true
    keyframes-name-pattern:
    no-descending-specificity: true
    no-duplicate-at-import-rules: true
    no-duplicate-selectors: true
    number-max-precision: 5
    property-no-vendor-prefix:
    scss/at-extend-no-missing-placeholder:
    scss/load-no-partial-leading-underscore: true
    scss/at-rule-no-unknown: true
    scss/dollar-variable-colon-space-after: always
    scss/dollar-variable-colon-space-before: never
    scss/dollar-variable-empty-line-before:
    scss/dollar-variable-first-in-block:
        - true
        - ignore:
              - comments
              - imports
    scss/dollar-variable-no-missing-interpolation: true
    scss/no-duplicate-dollar-variables:
        - true
        - ignoreInside: at-rule
    scss/no-duplicate-mixins: true
    scss/no-global-function-names: true
    scss/operator-no-unspaced: true
    rule-empty-line-before:
        - always
        - except:
              - after-single-line-comment
          ignore:
              - inside-block
    selector-class-pattern:
    selector-no-vendor-prefix:
    selector-pseudo-element-colon-notation: double
    shorthand-property-no-redundant-values:
    value-keyword-case:
        - lower
        - ignoreProperties:
              - "/^\\$/"
    order/properties-order:
        - - composes
          - all
          - position
          - z-index
          - top
          - right
          - bottom
          - left
          - display
          - overflow
          - width
          - min-width
          - max-width
          - height
          - min-height
          - max-height
          - box-sizing
          - flex
          - flex-basis
          - flex-direction
          - flex-flow
          - flex-grow
          - flex-shrink
          - flex-wrap
          - align-content
          - align-items
          - align-self
          - justify-content
          - order
          - padding
          - padding-top
          - padding-right
          - padding-bottom
          - padding-left
          - border
          - border-width
          - border-style
          - border-color
          - border-radius
          - border-top
          - border-top-width
          - border-top-style
          - border-top-color
          - border-top-radius
          - border-right
          - border-right-width
          - border-right-style
          - border-right-color
          - border-right-radius
          - border-bottom
          - border-bottom-width
          - border-bottom-style
          - border-bottom-color
          - border-bottom-radius
          - border-left
          - border-left-width
          - border-left-style
          - border-left-color
          - border-left-radius
          - margin
          - margin-top
          - margin-right
          - margin-bottom
          - margin-left
        - unspecified: bottomAlphabetical
