title: Site

layout:
    type: sections
    sections:
        info:
            label: '{{panel.options.site.info}}'
            collapsible: true
            fields: [title, author, description]

        advanced:
            label: '{{panel.options.site.advanced}}'
            collapsible: true
            collapsed: true
            fields: [metadata, routeAliases]

fields:
    title:
        type: text
        label: '{{panel.options.site.info.title}}'
        required: true

    author:
        type: text
        label: '{{panel.options.site.info.author}}'


    description:
        type: textarea
        label: '{{panel.options.site.info.description}}'

    metadata:
        type: array
        label: '{{panel.options.site.advanced.metadata}}'
        associative: true
        placeholderKey: '{{panel.options.site.advanced.metadata.name}}'
        placeholderValue: '{{panel.options.site.advanced.metadata.content}}'

    routeAliases:
        type: array
        label: '{{panel.options.site.advanced.aliases}}'
        associative: true
        placeholderKey: '{{panel.options.site.advanced.aliases.alias}}'
        placeholderValue: '{{panel.options.site.advanced.aliases.route}}'
